
# Development Docker Compose Override
# This file automatically applies in development when using docker-compose
version: '3.8'

services:
  # Development API Gateway Configuration
  api-gateway:
    ports:
      - "80:80"     # HTTP
      - "443:443"   # HTTPS  
      - "8080:80"   # HTTP (alternative port)
    volumes:
      # Mount nginx config for live editing
      - ./infrastructure/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./infrastructure/nginx/ssl:/etc/nginx/ssl:rw
      - api_gateway_logs:/var/log/nginx
      # Add volume for development SSL certificates
      - gateway_ssl_dev:/etc/nginx/ssl-dev
    environment:
      - NGINX_DEBUG=1
      - DOMAIN=ai-employee-platform.local
    # Override health check for development
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost/health", "||", "curl", "-f", "http://localhost/health"]
      interval: 15s
      timeout: 5s
      retries: 2
      start_period: 10s

  # Development database with exposed ports for debugging
  postgres:
    environment:
      - POSTGRES_DB=ai_employee_platform_dev
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=dev_password
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./database/migrations:/migrations:ro
      - ./database/seeds:/seeds:ro

  redis:
    ports:
      - "6379:6379"
    environment:
      - REDIS_APPENDONLY=no  # Faster for development
    
  # Development service overrides with debug ports
  auth-service:
    environment:
      - NODE_ENV=development
      - DEBUG=auth:*
      - LOG_LEVEL=debug
    ports:
      - "3001:3000"
      - "9001:9229"  # Debug port
    volumes:
      - ./services/auth-service/src:/app/src:ro
    
  ai-routing-service:
    environment:
      - NODE_ENV=development
      - DEBUG=ai:*
      - LOG_LEVEL=debug
    ports:
      - "3002:3000"
      - "9002:9229"  # Debug port
    volumes:
      - ./services/ai-routing-service/src:/app/src:ro

  billing-service:
    environment:
      - NODE_ENV=development
      - DEBUG=billing:*
      - LOG_LEVEL=debug
    ports:
      - "3003:3000"
      - "9003:9229"  # Debug port
    volumes:
      - ./services/billing-service/src:/app/src:ro

  user-management-service:
    environment:
      - NODE_ENV=development
      - DEBUG=users:*
      - LOG_LEVEL=debug
    ports:
      - "3004:3000"
      - "9004:9229"  # Debug port
    volumes:
      - ./services/user-management-service/src:/app/src:ro

  plugin-manager-service:
    environment:
      - NODE_ENV=development
      - DEBUG=plugins:*
      - LOG_LEVEL=debug
    ports:
      - "3005:3000"
      - "9005:9229"  # Debug port
    volumes:
      - ./services/plugin-manager-service/src:/app/src:ro

  notification-service:
    environment:
      - NODE_ENV=development
      - DEBUG=notifications:*
      - LOG_LEVEL=debug
    ports:
      - "3006:3000"
      - "9006:9229"  # Debug port
    volumes:
      - ./services/notification-service/src:/app/src:ro

  # Frontend development overrides
  admin-dashboard:
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=https://localhost
      - NEXT_TELEMETRY_DISABLED=1
      - FAST_REFRESH=true
    ports:
      - "3000:3000"
    volumes:
      - ./apps/admin-dashboard/src:/app/src:ro
      - ./apps/admin-dashboard/public:/app/public:ro

  employee-portal:
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=https://localhost
      - NEXT_TELEMETRY_DISABLED=1  
      - FAST_REFRESH=true
    ports:
      - "3100:3000"
    volumes:
      - ./apps/employee-portal/src:/app/src:ro
      - ./apps/employee-portal/public:/app/public:ro

volumes:
  postgres_dev_data:
    driver: local
  gateway_ssl_dev:
    driver: local
